---
title: "imapr - An R Interface to IMAP"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
response <- readRDS("tmp/data/response-list.rds")
search_all <- readRDS("tmp/data/response-search_all.rds")
```

`imapr` performs IMAP queries via curl.

## Installation

```{r installation, eval=FALSE}
require("devtools")

install_github("crazycapivara/imapr")
```

## Usage

```{r introduction, echo=TRUE, eval=TRUE}
library(imapr)

host <- "imaps://imap.gmail.com"

imap <- IMAP(host) %>% user("your_username", "your_password")
imap[c("url", "path")]
```

### List and select mailboxes

```{r cmd-list, echo=TRUE, eval=FALSE}
response <- imap %>% LIST() %>% execute()
```

```{r response-list, echo=TRUE, eval=TRUE}
response$content %>% cat()

imap %>% SELECT("INBOX") %>% .[c("url", "path")]
```

### Search for messages

```{r cmd-search, echo=TRUE, eval=FALSE}
search_all <- imap %>% SELECT("INBOX")
   %>% SEARCH("ALL") %>% execute() 
```

```{r response-search, echo=TRUE, eval=TRUE}
search_all$url
search_all$content %>% substr(1, 20)
## To be continued ##
```

## Run tests

```{r tests, echo=TRUE, eval=TRUE}
devtools::test(reporter = "tap")
```
